on:
  push:
    branches: main

name: rsconnect

jobs:
  rsconnect:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUBPAT }}
      SHINYAPPS_NAME: ${{ secrets.SHINYAPPSNAME }}
      SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPSTOKEN }}
      SHINYAPPS_SECRET: ${{ secrets.SHINYAPPSSECRET }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rsconnect, any::biglm, any::cpp11, any::prettyunits, any::progress, any::markdown
      - name: Deploy
        run: Rscript rsconnect.R
